### PR TITLE
Duplicate Item Alert

### LINKED ISSUE #6: 6. As a user, I want to be alerted when I’m entering an item that is the same as something already on my list so I can avoid duplicate items.
AC:
      * Show an error message if the user tries to submit a new item that has the exact same name as an existing item
      * Show an error message if the user tries to submit a new item that has the same name as an existing item, where capitalization has been normalized and punctuation has been removed
      * The user’s original input should be what gets saved in the database

### PR DESCRIPTION
**Pull request by sanrafa**
## Description

In this PR, we updated the `handleSubmit()` function in `AddItemView.jsx` to notify the user if the item they inputted in the form already exists, while considering its letter case or added special characters.

To accomplish this, we used the collection from the database to create an array of only the item values. We then mapped through the item values to make them lowercase and remove any special characters. We applied this change to the input value as well, then checked if the input value exists in the array we created. 

If it exists, we return a toast notification saying "Item already exists!" If it doesn't exist, the item is added to the database collection. 

## Related Issue

Closes #6 

## Acceptance Criteria

- [x] Show an error message if the user tries to submit a new item that has the exact same name as an existing item
- [x] Show an error message if the user tries to submit a new item that has the same name as an existing item, where capitalization has been normalized and punctuation has been removed
- [x] The user’s original input should be what gets saved in the database

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

### Before

preview-before

### After

preview-after

## Testing Steps / QA Criteria
1. Add an item to the form: "mangoes"
2. Add the same item with uppercase letters & special characters: "MaNGoEs!@#$"
3. You should expect the notification "Item already exists!"

### CODE REVIEW

**Review by danainjax — APPROVED** [review]
This was great work! I tested using "peanuts", "peanuts@@@", and "PEANUTS" and received an error message toast notification when the item already exists in the db.

**Review by devaratpatel — APPROVED** [review]

**Comment by devaratpatel** [comment]
Approved on my end! All the features work without issues! Solid work!

**Comment by yenly** [comment]
Before reviewing the code, I want to show you what I'm seeing on the deployment preview.
Screen Cast 2022-01-28 at 2 42 37 PM

**Comment by yenly** [comment]
Perhaps this will help you narrow down where the bug could be.
Screen Cast 2022-01-28 at 2 58 37 PM

**Comment by sanrafa** [comment]
This most recent commit should clear up that issue you were seeing, @yenly ! We weren't sure how to correct for misspellings without incorporating a dictionary, but we used the .split and .join methods to remove extra whitespace when comparing between user input and the existing items.

NOTE: If the user *does* intend to enter extra whitespace, it doesn't seem to get saved to the DB (one space between words regardless). We weren't sure how to track that down, or if it even needs to be fixed - perhaps it's safe to assume that extra spaces are typos

**Pull request merged**
